# Enhanced Tekton System for RepoSentry
# This file contains all enhanced Tekton resources for better pipeline identification

---
# Enhanced TriggerBinding - extracts rich metadata from RepoSentry webhooks
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: advanced-trigger-binding
  namespace: default
  labels:
    app.kubernetes.io/name: reposentry-advanced
    app.kubernetes.io/component: trigger-binding
    app.kubernetes.io/part-of: reposentry
spec:
  params:
  # 基础Git参数
  - name: git-url
    value: $(body.repository.clone_url)
  - name: git-revision
    value: $(body.after)
  - name: short-sha
    value: $(body.short_sha)
  - name: ref
    value: $(body.ref)
    
  # RepoSentry增强标识参数
  - name: provider
    value: $(body.metadata.provider)
  - name: event-type
    value: $(body.metadata.event_type)
  - name: repository-name
    value: $(body.metadata.repository_name)
  - name: repository-id
    value: $(body.metadata.repository_id)
  - name: organization
    value: $(body.metadata.organization)
  - name: project-name
    value: $(body.metadata.project_name)
  - name: branch
    value: $(body.metadata.branch)
  - name: commit-sha
    value: $(body.metadata.commit_sha)
  - name: trigger-source
    value: $(body.metadata.trigger_source)
  - name: trigger-id
    value: $(body.metadata.trigger_id)
  - name: reposentry-event-id
    value: $(body.metadata.reposentry_event_id)
    
  # 兼容性参数
  - name: message
    value: "$(body.metadata.trigger_source) $(body.metadata.event_type) on $(body.metadata.provider):$(body.metadata.organization)/$(body.metadata.project_name)@$(body.metadata.branch)"

---
# Enhanced TriggerTemplate - creates PipelineRuns with rich labels
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: advanced-trigger-template
  namespace: default
  labels:
    app.kubernetes.io/name: reposentry-advanced
    app.kubernetes.io/component: trigger-template
    app.kubernetes.io/part-of: reposentry
spec:
  params:
  # 基础参数
  - name: git-url
    description: Git repository URL
  - name: git-revision
    description: Git revision/commit SHA
    default: main
  - name: short-sha
    description: Short commit SHA
    default: ""
  - name: ref
    description: Git reference (refs/heads/main)
    default: "refs/heads/main"
    
  # RepoSentry增强参数
  - name: provider
    description: Git provider (github/gitlab)
    default: "unknown"
  - name: event-type
    description: Event type (branch_updated/branch_created)
    default: "unknown"
  - name: repository-name
    description: Full repository name (org/repo)
    default: "unknown/unknown"
  - name: repository-id
    description: Unique repository identifier
    default: "unknown-repo"
  - name: organization
    description: Organization/user name
    default: "unknown"
  - name: project-name
    description: Project/repository name only
    default: "unknown"
  - name: branch
    description: Branch name
    default: "main"
  - name: commit-sha
    description: Full commit SHA
    default: ""
  - name: trigger-source
    description: Trigger source (reposentry)
    default: "unknown"
  - name: trigger-id
    description: Unique trigger identifier
    default: "unknown"
  - name: reposentry-event-id
    description: RepoSentry event ID
    default: ""
  - name: message
    description: Trigger message
    default: "Triggered by webhook!"
    
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: "$(tt.params.provider)-$(tt.params.project-name)-"
      labels:
        # 增强标签系统 - RepoSentry命名空间
        reposentry.dev/provider: "$(tt.params.provider)"
        reposentry.dev/organization: "$(tt.params.organization)"
        reposentry.dev/project: "$(tt.params.project-name)"
        reposentry.dev/repository: "$(tt.params.repository-id)"
        reposentry.dev/branch: "$(tt.params.branch)"
        reposentry.dev/event-type: "$(tt.params.event-type)"
        reposentry.dev/trigger-source: "$(tt.params.trigger-source)"
        
        # Tekton标准标签
        tekton.dev/pipeline: advanced-pipeline
        triggers.tekton.dev/eventlistener: hello-event-listener
        triggers.tekton.dev/trigger: advanced-trigger
        
        # 附加标识标签
        app.kubernetes.io/name: reposentry-pipeline
        app.kubernetes.io/component: pipeline-run
        app.kubernetes.io/part-of: reposentry
        app.kubernetes.io/managed-by: tekton-triggers
        
      annotations:
        # 增强注解
        reposentry.dev/event-id: "$(tt.params.reposentry-event-id)"
        reposentry.dev/trigger-id: "$(tt.params.trigger-id)"
        reposentry.dev/commit-sha: "$(tt.params.commit-sha)"
        reposentry.dev/short-sha: "$(tt.params.short-sha)"
        reposentry.dev/git-ref: "$(tt.params.ref)"
        
    spec:
      params:
      - name: git-url
        value: "$(tt.params.git-url)"
      - name: git-revision
        value: "$(tt.params.git-revision)"
      - name: provider
        value: "$(tt.params.provider)"
      - name: event-type
        value: "$(tt.params.event-type)"
      - name: repository-name
        value: "$(tt.params.repository-name)"
      - name: organization
        value: "$(tt.params.organization)"
      - name: project-name
        value: "$(tt.params.project-name)"
      - name: branch
        value: "$(tt.params.branch)"
      - name: trigger-info
        value: "$(tt.params.message)"
      pipelineRef:
        name: advanced-pipeline

---
# Enhanced Pipeline - displays rich context information
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: advanced-pipeline
  namespace: default
  labels:
    app.kubernetes.io/name: reposentry-advanced
    app.kubernetes.io/component: pipeline
    app.kubernetes.io/part-of: reposentry
spec:
  params:
  - name: git-url
    type: string
    description: Git repository URL
  - name: git-revision
    type: string
    description: Git revision
    default: main
  - name: provider
    type: string
    description: Git provider (github/gitlab)
    default: unknown
  - name: event-type
    type: string
    description: Event type
    default: unknown
  - name: repository-name
    type: string
    description: Repository name
    default: unknown
  - name: organization
    type: string
    description: Organization name
    default: unknown
  - name: project-name
    type: string
    description: Project name
    default: unknown
  - name: branch
    type: string
    description: Branch name
    default: main
  - name: trigger-info
    type: string
    description: Trigger information
    default: "Unknown trigger"
    
  tasks:
  - name: display-context
    taskSpec:
      params:
      - name: git-url
        type: string
      - name: git-revision
        type: string
      - name: provider
        type: string
      - name: event-type
        type: string
      - name: repository-name
        type: string
      - name: organization
        type: string
      - name: project-name
        type: string
      - name: branch
        type: string
      - name: trigger-info
        type: string
      steps:
      - name: show-advanced-info
        image: alpine:latest
        script: |
          #!/bin/sh
          echo "=============================================="
          echo "🚀 REPOSENTRY ENHANCED PIPELINE EXECUTION"
          echo "=============================================="
          echo ""
          echo "📍 SOURCE INFORMATION:"
          echo "   🔗 Provider: $(params.provider)"
          echo "   🏢 Organization: $(params.organization)"
          echo "   📦 Project: $(params.project-name)"
          echo "   📁 Repository: $(params.repository-name)"
          echo "   🌿 Branch: $(params.branch)"
          echo ""
          echo "⚡ EVENT DETAILS:"
          echo "   📝 Event Type: $(params.event-type)"
          echo "   💬 Trigger Info: $(params.trigger-info)"
          echo ""
          echo "🔧 GIT DETAILS:"
          echo "   🌐 Git URL: $(params.git-url)"
          echo "   📄 Git Revision: $(params.git-revision)"
          echo ""
          echo "=============================================="
          echo "✅ Enhanced Pipeline executed successfully!"
          echo "=============================================="
    params:
    - name: git-url
      value: $(params.git-url)
    - name: git-revision
      value: $(params.git-revision)
    - name: provider
      value: $(params.provider)
    - name: event-type
      value: $(params.event-type)
    - name: repository-name
      value: $(params.repository-name)
    - name: organization
      value: $(params.organization)
    - name: project-name
      value: $(params.project-name)
    - name: branch
      value: $(params.branch)
    - name: trigger-info
      value: $(params.trigger-info)

