# RepoSentry CloudEvents 标准系统 - 一键部署包
# 包含：Pipeline, TriggerBinding, TriggerTemplate, EventListener
# 版本：v2.0 (CloudEvents 1.0 标准)

---
# RepoSentry 标准 Pipeline - CloudEvents 兼容
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: reposentry-ci-pipeline
  namespace: default
  labels:
    app.kubernetes.io/name: reposentry
    app.kubernetes.io/component: pipeline
    app.kubernetes.io/version: "2.0"
    reposentry.dev/format: cloudevents
  annotations:
    description: "RepoSentry CloudEvents standard pipeline"
    reposentry.dev/payload-format: "cloudevents-1.0"
spec:
  params:
    # === 核心仓库参数 ===
    - name: provider
      type: string
      description: "Git provider (github/gitlab)"
    - name: organization
      type: string
      description: "Repository organization/owner"
    - name: repository-name
      type: string
      description: "Repository name"
    - name: repository-url
      type: string
      description: "Repository URL"
    - name: branch-name
      type: string
      description: "Git branch name"
    - name: commit-sha
      type: string
      description: "Git commit SHA"
    - name: commit-message
      type: string
      description: "Commit message"
    - name: event-type
      type: string
      description: "Event type (branch_updated/branch_created/branch_deleted)"
    - name: trigger-id
      type: string
      description: "Unique trigger identifier"
    
  tasks:
    - name: display-cloudevents-info
      taskSpec:
        params:
          - name: provider
          - name: organization
          - name: repository-name
          - name: repository-url
          - name: branch-name
          - name: commit-sha
          - name: commit-message
          - name: event-type
          - name: trigger-id
        steps:
          - name: display-info
            image: alpine:latest
            script: |
              #!/bin/sh
              echo "=== 🚀 RepoSentry CloudEvents CI Pipeline v2.0 ==="
              echo ""
              echo "📋 CloudEvents Standard Format Detected ✅"
              echo ""
              echo "📍 Repository Information:"
              echo "  🔗 Provider: $(params.provider)"
              echo "  🏢 Organization: $(params.organization)"
              echo "  📦 Repository: $(params.repository-name)"
              echo "  🌐 URL: $(params.repository-url)"
              echo ""
              echo "🌿 Branch & Commit Information:"
              echo "  🌱 Branch: $(params.branch-name)"
              echo "  📝 Commit SHA: $(params.commit-sha)"
              echo "  💬 Message: $(params.commit-message)"
              echo ""
              echo "⚡ Event Information:"
              echo "  🎯 Type: $(params.event-type)"
              echo "  🆔 Trigger ID: $(params.trigger-id)"
              echo ""
              echo "✅ All CloudEvents parameters successfully extracted!"
              echo "🎯 Pipeline ready for custom CI/CD tasks..."
              echo ""
              echo "📚 Docs: docs/zh/tekton-integration-guide.md"
      params:
        - name: provider
          value: $(params.provider)
        - name: organization
          value: $(params.organization)
        - name: repository-name
          value: $(params.repository-name)
        - name: repository-url
          value: $(params.repository-url)
        - name: branch-name
          value: $(params.branch-name)
        - name: commit-sha
          value: $(params.commit-sha)
        - name: commit-message
          value: $(params.commit-message)
        - name: event-type
          value: $(params.event-type)
        - name: trigger-id
          value: $(params.trigger-id)

---
# RepoSentry 标准 TriggerBinding - CloudEvents 路径
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: reposentry-basic-binding
  namespace: default
  labels:
    app.kubernetes.io/name: reposentry
    app.kubernetes.io/component: triggerbinding
    app.kubernetes.io/version: "2.0"
    reposentry.dev/format: cloudevents
  annotations:
    description: "RepoSentry CloudEvents standard TriggerBinding"
    reposentry.dev/payload-format: "cloudevents-1.0"
    reposentry.dev/migration-guide: "docs/zh/tekton-integration-guide.md"
spec:
  params:
    # === 核心仓库信息 - CloudEvents 标准路径 ===
    - name: provider
      value: $(body.data.repository.provider)
    - name: organization
      value: $(body.data.repository.organization)
    - name: repository-name
      value: $(body.data.repository.name)
    - name: repository-url
      value: $(body.data.repository.url)
    
    # === 分支和提交信息 ===
    - name: branch-name
      value: $(body.data.branch.name)
    - name: commit-sha
      value: $(body.data.commit.sha)
    - name: commit-message
      value: $(body.data.commit.message)
    
    # === 事件信息 ===
    - name: event-type
      value: $(body.data.event.type)
    - name: trigger-id
      value: $(body.data.event.trigger_id)

---
# RepoSentry 标准 TriggerTemplate - 丰富标签
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: reposentry-basic-template
  namespace: default
  labels:
    app.kubernetes.io/name: reposentry
    app.kubernetes.io/component: triggertemplate
    app.kubernetes.io/version: "2.0"
    reposentry.dev/format: cloudevents
  annotations:
    description: "RepoSentry CloudEvents standard TriggerTemplate"
    reposentry.dev/payload-format: "cloudevents-1.0"
spec:
  params:
    - name: provider
      description: "Git provider (github/gitlab)"
    - name: organization
      description: "Repository organization/owner"
    - name: repository-name
      description: "Repository name"
    - name: repository-url
      description: "Repository URL"
    - name: branch-name
      description: "Git branch name"
    - name: commit-sha
      description: "Git commit SHA"
    - name: commit-message
      description: "Commit message"
    - name: event-type
      description: "Event type"
    - name: trigger-id
      description: "Trigger identifier"
      
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: "reposentry-$(tt.params.provider)-$(tt.params.organization)-"
        labels:
          # === RepoSentry 标准标签 (v2.0) ===
          reposentry.dev/provider: $(tt.params.provider)
          reposentry.dev/organization: $(tt.params.organization)
          reposentry.dev/repository: $(tt.params.repository-name)
          reposentry.dev/branch: $(tt.params.branch-name)
          reposentry.dev/event-type: $(tt.params.event-type)
          reposentry.dev/trigger-id: $(tt.params.trigger-id)
          reposentry.dev/format: "cloudevents"
          reposentry.dev/version: "2.0"
          
          # === Tekton 标准标签 ===
          tekton.dev/pipeline: reposentry-ci-pipeline
          
          # === 应用标签 ===
          app.kubernetes.io/name: reposentry
          app.kubernetes.io/component: pipelinerun
          app.kubernetes.io/managed-by: reposentry-webhook
          
        annotations:
          # === 丰富的注解信息 ===
          reposentry.dev/repository-url: $(tt.params.repository-url)
          reposentry.dev/commit-message: $(tt.params.commit-message)
          reposentry.dev/commit-sha: $(tt.params.commit-sha)
          reposentry.dev/payload-format: "cloudevents-1.0"
          description: "Triggered by RepoSentry $(tt.params.provider) webhook"
          
      spec:
        pipelineRef:
          name: reposentry-ci-pipeline
        params:
          - name: provider
            value: $(tt.params.provider)
          - name: organization
            value: $(tt.params.organization)
          - name: repository-name
            value: $(tt.params.repository-name)
          - name: repository-url
            value: $(tt.params.repository-url)
          - name: branch-name
            value: $(tt.params.branch-name)
          - name: commit-sha
            value: $(tt.params.commit-sha)
          - name: commit-message
            value: $(tt.params.commit-message)
          - name: event-type
            value: $(tt.params.event-type)
          - name: trigger-id
            value: $(tt.params.trigger-id)

---
# RepoSentry 标准 EventListener - CloudEvents 处理
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: reposentry-basic-eventlistener
  namespace: default
  labels:
    app.kubernetes.io/name: reposentry
    app.kubernetes.io/component: eventlistener
    app.kubernetes.io/version: "2.0"
    reposentry.dev/format: cloudevents
  annotations:
    description: "RepoSentry CloudEvents standard EventListener"
    reposentry.dev/payload-format: "cloudevents-1.0"
    reposentry.dev/docs: "docs/zh/tekton-integration-guide.md"
spec:
  serviceAccountName: tekton-triggers-serviceaccount
  triggers:
    - name: reposentry-cloudevents-trigger
      bindings:
        - ref: reposentry-basic-binding
      template:
        ref: reposentry-basic-template
