# RepoSentry CloudEvents 标准系统 - 一键部署包
# 包含：Pipeline, TriggerBinding, TriggerTemplate, EventListener
# 版本：v2.0 (CloudEvents 1.0 标准)

---
# NOTE: The main pipeline is now defined in reposentry-demo-pipeline.yaml
# This file only contains the Tekton Triggers configuration

---
# RepoSentry 标准 TriggerBinding - CloudEvents 路径
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: reposentry-basic-binding
  namespace: default
  labels:
    app.kubernetes.io/name: reposentry
    app.kubernetes.io/component: triggerbinding
    app.kubernetes.io/version: "2.0"
    reposentry.dev/format: cloudevents
  annotations:
    description: "RepoSentry CloudEvents standard TriggerBinding"
    reposentry.dev/payload-format: "cloudevents-1.0"
    reposentry.dev/migration-guide: "docs/zh/tekton-integration-guide.md"
spec:
  params:
    # === 核心仓库信息 - CloudEvents 标准路径 ===
    - name: provider
      value: $(body.data.repository.provider)
    - name: organization
      value: $(body.data.repository.organization)
    - name: repository-name
      value: $(body.data.repository.name)
    - name: repository-url
      value: $(body.data.repository.url)
    
    # === 分支和提交信息 ===
    - name: branch-name
      value: $(body.data.branch.name)
    - name: commit-sha
      value: $(body.data.commit.sha)
    - name: commit-message
      value: $(body.data.commit.message)
    
    # === 事件信息 ===
    - name: event-type
      value: $(body.data.event.type)
    - name: trigger-id
      value: $(body.data.event.trigger_id)

---
# RepoSentry 标准 TriggerTemplate - 丰富标签
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: reposentry-basic-template
  namespace: default
  labels:
    app.kubernetes.io/name: reposentry
    app.kubernetes.io/component: triggertemplate
    app.kubernetes.io/version: "2.0"
    reposentry.dev/format: cloudevents
  annotations:
    description: "RepoSentry CloudEvents standard TriggerTemplate"
    reposentry.dev/payload-format: "cloudevents-1.0"
spec:
  params:
    - name: provider
      description: "Git provider (github/gitlab)"
    - name: organization
      description: "Repository organization/owner"
    - name: repository-name
      description: "Repository name"
    - name: repository-url
      description: "Repository URL"
    - name: branch-name
      description: "Git branch name"
    - name: commit-sha
      description: "Git commit SHA"
    - name: commit-message
      description: "Commit message"
    - name: event-type
      description: "Event type"
    - name: trigger-id
      description: "Trigger identifier"
      
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: "reposentry-$(tt.params.provider)-$(tt.params.organization)-"
        labels:
          # === RepoSentry 标准标签 (v2.0) ===
          reposentry.dev/provider: $(tt.params.provider)
          reposentry.dev/organization: $(tt.params.organization)
          reposentry.dev/repository: $(tt.params.repository-name)
          reposentry.dev/branch: $(tt.params.branch-name)
          reposentry.dev/event-type: $(tt.params.event-type)
          reposentry.dev/trigger-id: $(tt.params.trigger-id)
          reposentry.dev/format: "cloudevents"
          reposentry.dev/version: "2.0"
          
          # === Tekton 标准标签 ===
          tekton.dev/pipeline: reposentry-demo-pipeline
          
          # === 应用标签 ===
          app.kubernetes.io/name: reposentry
          app.kubernetes.io/component: pipelinerun
          app.kubernetes.io/managed-by: reposentry-webhook
          
        annotations:
          # === 丰富的注解信息 ===
          reposentry.dev/repository-url: $(tt.params.repository-url)
          reposentry.dev/commit-message: $(tt.params.commit-message)
          reposentry.dev/commit-sha: $(tt.params.commit-sha)
          reposentry.dev/payload-format: "cloudevents-1.0"
          description: "Triggered by RepoSentry $(tt.params.provider) webhook"
          
      spec:
        pipelineRef:
          name: reposentry-demo-pipeline
        params:
          - name: provider
            value: $(tt.params.provider)
          - name: organization
            value: $(tt.params.organization)
          - name: repository-name
            value: $(tt.params.repository-name)
          - name: repository-url
            value: $(tt.params.repository-url)
          - name: branch-name
            value: $(tt.params.branch-name)
          - name: commit-sha
            value: $(tt.params.commit-sha)
          - name: commit-message
            value: $(tt.params.commit-message)
          - name: event-type
            value: $(tt.params.event-type)
          - name: trigger-id
            value: $(tt.params.trigger-id)
          - name: tekton-path
            value: ".tekton"
          - name: target-namespace-prefix
            value: "reposentry"
          - name: github-token
            value: ""
        workspaces:
          - name: source-code
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - name: tekton-resources
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 500Mi

---
# RepoSentry 标准 EventListener - CloudEvents 处理
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: reposentry-basic-eventlistener
  namespace: default
  labels:
    app.kubernetes.io/name: reposentry
    app.kubernetes.io/component: eventlistener
    app.kubernetes.io/version: "2.0"
    reposentry.dev/format: cloudevents
  annotations:
    description: "RepoSentry CloudEvents standard EventListener"
    reposentry.dev/payload-format: "cloudevents-1.0"
    reposentry.dev/docs: "docs/zh/tekton-integration-guide.md"
spec:
  serviceAccountName: tekton-triggers-serviceaccount
  triggers:
    - name: reposentry-cloudevents-trigger
      bindings:
        - ref: reposentry-basic-binding
      template:
        ref: reposentry-basic-template
