version: '3.8'

services:
  reposentry:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    image: reposentry:latest
    container_name: reposentry
    restart: unless-stopped
    
    # Environment variables
    environment:
      - RS_LOG_LEVEL=info
      - RS_LOG_FORMAT=json
      - RS_DATA_DIR=/app/data
      # Add your tokens here:
      # - GITHUB_TOKEN=your_github_token
      # - GITLAB_TOKEN=your_gitlab_token
    
    # Ports
    ports:
      - "8080:8080"  # Health check and API
    
    # Volumes
    volumes:
      - ./config.yaml:/app/configs/config.yaml:ro  # Configuration
      - reposentry-data:/app/data                   # Data persistence
      - reposentry-logs:/app/logs                   # Logs
    
    # Health check
    healthcheck:
      test: ["/app/reposentry", "status", "--host=localhost", "--port=8080"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    
    # Security
    user: "1000:1000"  # Run as non-root user
    read_only: true
    tmpfs:
      - /tmp:size=100M,noexec,nosuid,nodev
    
    # Capabilities
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

volumes:
  reposentry-data:
    driver: local
  reposentry-logs:
    driver: local

networks:
  default:
    name: reposentry-network
