apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: advanced-trigger-binding
  namespace: default
spec:
  params:
  # 基础Git参数
  - name: git-url
    value: $(body.repository.clone_url)
  - name: git-revision
    value: $(body.after)
  - name: short-sha
    value: $(body.short_sha)
  - name: ref
    value: $(body.ref)
    
  # RepoSentry增强标识参数
  - name: provider
    value: $(body.metadata.provider)
  - name: event-type
    value: $(body.metadata.event_type)
  - name: repository-name
    value: $(body.metadata.repository_name)
  - name: repository-id
    value: $(body.metadata.repository_id)
  - name: organization
    value: $(body.metadata.organization)
  - name: project-name
    value: $(body.metadata.project_name)
  - name: branch
    value: $(body.metadata.branch)
  - name: commit-sha
    value: $(body.metadata.commit_sha)
  - name: trigger-source
    value: $(body.metadata.trigger_source)
  - name: trigger-id
    value: $(body.metadata.trigger_id)
  - name: reposentry-event-id
    value: $(body.metadata.reposentry_event_id)
    
  # 兼容性参数
  - name: message
    value: "$(body.metadata.trigger_source) $(body.metadata.event_type) on $(body.metadata.provider):$(body.metadata.organization)/$(body.metadata.project_name)@$(body.metadata.branch)"
