apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: advanced-pipeline
  namespace: default
spec:
  params:
  - name: git-url
    type: string
    description: Git repository URL
  - name: git-revision
    type: string
    description: Git revision
    default: main
  - name: provider
    type: string
    description: Git provider (github/gitlab)
    default: unknown
  - name: event-type
    type: string
    description: Event type
    default: unknown
  - name: repository-name
    type: string
    description: Repository name
    default: unknown
  - name: organization
    type: string
    description: Organization name
    default: unknown
  - name: project-name
    type: string
    description: Project name
    default: unknown
  - name: branch
    type: string
    description: Branch name
    default: main
  - name: trigger-info
    type: string
    description: Trigger information
    default: "Unknown trigger"
    
  tasks:
  - name: display-context
    taskSpec:
      params:
      - name: git-url
        type: string
      - name: git-revision
        type: string
      - name: provider
        type: string
      - name: event-type
        type: string
      - name: repository-name
        type: string
      - name: organization
        type: string
      - name: project-name
        type: string
      - name: branch
        type: string
      - name: trigger-info
        type: string
      steps:
      - name: show-advanced-info
        image: alpine:latest
        script: |
          #!/bin/sh
          echo "=============================================="
          echo "🚀 REPOSENTRY ENHANCED PIPELINE EXECUTION"
          echo "=============================================="
          echo ""
          echo "📍 SOURCE INFORMATION:"
          echo "   🔗 Provider: $(params.provider)"
          echo "   🏢 Organization: $(params.organization)"
          echo "   📦 Project: $(params.project-name)"
          echo "   📁 Repository: $(params.repository-name)"
          echo "   🌿 Branch: $(params.branch)"
          echo ""
          echo "⚡ EVENT DETAILS:"
          echo "   📝 Event Type: $(params.event-type)"
          echo "   💬 Trigger Info: $(params.trigger-info)"
          echo ""
          echo "🔧 GIT DETAILS:"
          echo "   🌐 Git URL: $(params.git-url)"
          echo "   📄 Git Revision: $(params.git-revision)"
          echo ""
          echo "=============================================="
          echo "✅ Enhanced Pipeline executed successfully!"
          echo "=============================================="
    params:
    - name: git-url
      value: $(params.git-url)
    - name: git-revision
      value: $(params.git-revision)
    - name: provider
      value: $(params.provider)
    - name: event-type
      value: $(params.event-type)
    - name: repository-name
      value: $(params.repository-name)
    - name: organization
      value: $(params.organization)
    - name: project-name
      value: $(params.project-name)
    - name: branch
      value: $(params.branch)
    - name: trigger-info
      value: $(params.trigger-info)
