# Minimal configuration for testing
app:
  name: "reposentry"
  data_dir: "/tmp/reposentry"

tekton:
  event_listener_url: "http://localhost:8080/webhook"

repositories:
  - name: "test-repo"
    url: "https://github.com/test/repo"
    provider: "github"
    token: "fake-token-for-testing"
    branch_regex: ".*"
    enabled: true

security:
  allowed_env_vars:
    - "GITHUB_TOKEN"
    - "*_TOKEN"
