# My Repository Configuration
# This file contains only my repositories - easy to edit and manage!

# My GitHub repositories
github_repos:
  - name: "taap-poc-github"
    url: "https://github.com/johnnynv/TaaP_POC.git"
    branch_regex: "^(main|dev)$"
    enabled: true
    polling_interval: "1m"  # Fast polling for testing

# My GitLab Enterprise repositories
gitlab_repos:
  - name: "taap-poc-gitlab"
    url: "https://gitlab-master.nvidia.com/johnnyj/taap_poc_gitlab.git"
    branch_regex: "^(main)$"
    enabled: true
    api_base_url: "https://gitlab-master.nvidia.com/api/v4"

# Test mode settings
polling_overrides:
  test_mode: true   # Enable test mode for faster polling
  interval: "1m"    # Poll every minute during testing
