basePath: /
definitions:
  JSONResponse:
    description: Standard API response wrapper
    properties:
      data: {}
      error:
        type: string
      success:
        example: true
        type: boolean
      timestamp:
        example: "2023-12-01T10:00:00Z"
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@reposentry.dev
    name: RepoSentry Support
    url: https://github.com/johnnynv/RepoSentry
  description: |-
    A lightweight, cloud-native sentinel for monitoring GitLab and GitHub repositories
    This API provides endpoints for managing repository monitoring, viewing status, and accessing metrics.
  license:
    name: MIT
    url: https://github.com/johnnynv/RepoSentry/blob/main/LICENSE
  title: RepoSentry API
  version: "1.0"
paths:
  /api/events:
    get:
      consumes:
      - application/json
      description: Get events with pagination support
      parameters:
      - default: 50
        description: Number of events to return (max 1000)
        in: query
        name: limit
        type: integer
      - default: 0
        description: Number of events to skip
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Paginated list of events
          schema:
            allOf:
            - $ref: '#/definitions/JSONResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: List events
      tags:
      - Events
  /api/repositories:
    get:
      consumes:
      - application/json
      description: Get all configured repositories with their monitoring status
      produces:
      - application/json
      responses:
        "200":
          description: List of repositories
          schema:
            allOf:
            - $ref: '#/definitions/JSONResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: List repositories
      tags:
      - Repositories
  /health:
    get:
      consumes:
      - application/json
      description: Returns the overall health status of all RepoSentry components
      produces:
      - application/json
      responses:
        "200":
          description: Healthy
          schema:
            allOf:
            - $ref: '#/definitions/JSONResponse'
            - properties:
                data:
                  type: object
              type: object
        "503":
          description: Unhealthy
          schema:
            allOf:
            - $ref: '#/definitions/JSONResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Get system health
      tags:
      - Health
  /health/live:
    get:
      consumes:
      - application/json
      description: Kubernetes liveness probe endpoint - simple alive status
      produces:
      - application/json
      responses:
        "200":
          description: Alive
          schema:
            allOf:
            - $ref: '#/definitions/JSONResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Liveness probe
      tags:
      - Health
  /health/ready:
    get:
      consumes:
      - application/json
      description: Kubernetes readiness probe endpoint - ready status
      produces:
      - application/json
      responses:
        "200":
          description: Ready
          schema:
            allOf:
            - $ref: '#/definitions/JSONResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Readiness probe
      tags:
      - Health
  /metrics:
    get:
      consumes:
      - application/json
      description: Returns application metrics and statistics
      produces:
      - application/json
      responses:
        "200":
          description: Application metrics
          schema:
            allOf:
            - $ref: '#/definitions/JSONResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Get metrics
      tags:
      - Metrics
  /status:
    get:
      consumes:
      - application/json
      description: Returns runtime status and component information
      produces:
      - application/json
      responses:
        "200":
          description: System status
          schema:
            allOf:
            - $ref: '#/definitions/JSONResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Get system status
      tags:
      - Status
  /version:
    get:
      consumes:
      - application/json
      description: Returns API and application version details
      produces:
      - application/json
      responses:
        "200":
          description: Version information
          schema:
            allOf:
            - $ref: '#/definitions/JSONResponse'
            - properties:
                data:
                  type: object
              type: object
      summary: Get version information
      tags:
      - System
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    description: Bearer token for API authentication
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: Health check and readiness endpoints
  name: Health
- description: System status and runtime information
  name: Status
- description: Repository management and monitoring
  name: Repositories
- description: Event history and processing
  name: Events
- description: Application metrics and statistics
  name: Metrics
- description: System information and version
  name: System
